runtime: python37

entrypoint: gunicorn -b :$PORT flaskr:app

handlers:
- url: /static
  static_dir: static
  secure: always

- url: /favicon.ico
  static_files: static/favicon.ico
  upload: static/favicon.ico
  secure: always

- url: /.*
  script: auto
  secure: always

env_variables:
  MAIL_PASS: internreq
  DB_PASS: GearGrinders1!
  DB_CONNECTION: birmingham4test:us-east4:internreq-1